# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
skills = [
  'agile',
  'apache',
  'actionscript',
  'analytics',
  'android',
  'accounting',
  'bookkeeping',
  'branding',
  'business development',
  'business analysis',
  'business',
  'customer service',
  'consulting',
  'cold calling',
  'corporate law',
  'corporate tax',
  'css',
  'c',
  'chef',
  'clojure',
  'c++',
  'objective c',
  'computer science',
  'drawing',
  'design',
  'databases',
  'data analysis',
  'data mining',
  'data modeling',
  'django',
  'excel',
  'economics',
  'eclipse',
  'erlang',
  'fortran',
  'flash',
  'facilities management',
  'financial analysis',
  'firewalls',
  'financial reporting',
  'financial modeling',
  'fundraising',
  'graphics',
  'google analytics',
  'game development',
  'game design',
  'github',
  'gis',
  'git',
  'graphic design',
  'html 5',
  'hr',
  'human resources',
  'hadoop',
  'illustrator',
  'illustration',
  'indesign',
  'interviews',
  'interviewing',
  'invoicing',
  'identity management',
  'ios',
  'ios development',
  'it management',
  'it recruitment',
  'it strategy',
  'it operations',
  'java',
  'javascript',
  'jruby',
  'json',
  'joomla',
  'jquery',
  'keynote',
  'logistics management',
  'logistics',
  'law',
  'licensing',
  'liability',
  'microsoft office',
  'market analysis',
  'marketing',
  'management',
  'microsoft excel',
  'mongo',
  'nonprofits',
  'networking',
  'network security',
  'network administration',
  'negotiation',
  'nosql',
  'oop',
  'os x',
  'operations management',
  'office management',
  'operational planning',
  'organizational development',
  'organizational leadership',
  'outlook',
  'patents',
  'packaging',
  'payments',
  'payroll',
  'peoplesoft',
  'public speaking',
  'project management',
  'powerpoint',
  'package design',
  'print design',
  'php',
  'perl',
  'python',
  'quickbooks',
  'quality control',
  'qualitative research',
  'research',
  'r&d',
  'ruby',
  'rails',
  'ruby on rails',
  'risk management',
  'risk analysis',
  'risk assessment',
  'routing',
  'routers',
  'r',
  'servers',
  'scala',
  'sql',
  'spss',
  'sales',
  'sap',
  'sales operations',
  'sales management',
  'seo',
  'software development',
  'social networking',
  'social media',
  'strategic planning',
  'supply chain',
  'supply chain management',
  'technical writing',
  'tcp/ip',
  'tax',
  'talent acquisition',
  'tax law',
  'tax preparation',
  'team management',
  'technical recruiting',
  'tdd',
  'testing',
  'unix',
  'user experience',
  'ux',
  'ux design',
  'user interface design',
  'valuation',
  'variance analysis',
  'venture capital',
  'wordpress',
  'web development',
  'creative writing',
  'writing',
  'warehouse management',
  'web analytics',
  'web applications',
  'web services',
  'web design',
]
  
interests = [
  'climbing',
  'fencing',
  'judo',
  'taekwondo',
  'martial arts',
  'mma',
  'boxing',
  'biking',
  'bicycles',
  'motorcycles',
  'books',
  'reading',
  'food',
  'cooking',
  'eating',
  'music',
  'theater',
  'hiking',
  'camping',
  'art',
  'painting',
  'drawing',
  'design',
  'baking',
  'cars',
  'boats',
  'yoga',
  'architecture',
  'dogs',
  'animals',
  'cats',
  'rock climbing',
  'gaming',
  'video games',
  'education',
  'mentoring',
  'tutoring',
  'carpentry',
  'computers',
  'science',
  'philanthrophy',
  'philosophy',
  'fashion',
  'clothes',
  'fitness',
  'health',
  'wellness',
  'sports',
  'investing',
  'soccer',
  'football',
  'basketball',
  'golf',
  'baseball',
  'hockey',
  'computers',
  'writing',
  'singing',
  'dancing',
  'creative writing',
  'drinking',
  'socializing',
  'hip hop',
  'jazz',
  'edm',
  'electronic music',
  'juggling',
  'judo',
  'kung fu',
  'rugby'
]

skills.each do |s|
  puts "creating skill " + s
  Skill.find_or_create_by_name(s)
end

interests.each do |i|
  puts "creating interest " + i
  Interest.find_or_create_by_name(i)
end